### ISSUE TITLE
Error during IRI Latest Milestone updating

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#103]
## Description
`IndexOutOfBounds` exception on IRI init.

## Environment
* Full-node
  * node10
  * devorg
* IRI version
  * 1.5.5 - [DLTLab dev branch](https://github.com/DLTcollab/iri)
## Steps To Reproduce
It can't reproduce this issue on vanilla IRI.

IRI launch script
```
# Run IRI service
nohup java -server \
        -Xmx6g -Xms6g -Xss1m -Xmn512m \
        -XX:+UseParallelGC \
        -XX:InitiatingHeapOccupancyPercent=0 \
        -XX:ReservedCodeCacheSize=1843200k \
        -XX:CodeCacheMinimumFreeSpace=2m \
        -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 \
        -XX:+UseCompressedOops \
        -Djava.awt.headless=true \
        -jar $IRI \
        --config config-iri-dcurl \
	-Djava.library.path="." --pearldiver-exlib dcurl \
	--remote-limit-api 'removeNeighbors, addNeighbors' --remote > nohup.out &
```

Output:
```
11/14 14:17:13.516 [Latest Milestone Tracker] ERROR com.iota.iri.MilestoneTracker - Error during Latest Milestone updating
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[na:1.8.0_181]
	at java.util.LinkedList.get(LinkedList.java:476) ~[na:1.8.0_181]
	at com.iota.iri.MilestoneTracker.validateMilestone(MilestoneTracker.java:210) ~[iri-1.5.5-experimental.jar:na]
	at com.iota.iri.MilestoneTracker.lambda$init$0(MilestoneTracker.java:112) ~[iri-1.5.5-experimental.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
11/14 14:17:13.644 [XNIO-1 task-10] INFO  com.iota.iri.service.API - Tip selection failed: This operations cannot be executed: The subtangle has not been updated yet.
11/14 14:17:13.790 [Latest Milestone Tracker] ERROR com.iota.iri.MilestoneTracker - Error during Latest Milestone updating
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[na:1.8.0_181]
	at java.util.LinkedList.get(LinkedList.java:476) ~[na:1.8.0_181]
	at com.iota.iri.MilestoneTracker.validateMilestone(MilestoneTracker.java:210) ~[iri-1.5.5-experimental.jar:na]
	at com.iota.iri.MilestoneTracker.lambda$init$0(MilestoneTracker.java:112) ~[iri-1.5.5-experimental.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

GetNodeInfo API response
```
{
    "appName": "IRI",
    "appVersion": "1.5.5",
    "duration": 0,
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 6638547616,
    "jreMaxMemory": 8443658240,
    "jreTotalMemory": 8443658240,
    "jreVersion": "1.8.0_181",
    "latestMilestone": "DD9IKQIOTUZJXWKIYXSOSNUFGGKNPBCWSPAIXTCUTAUJUKGUHUWTMK9OHDMUIDM9MDUD9XL99HWHA9999",
    "latestMilestoneIndex": 879917,
    "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestSolidSubtangleMilestoneIndex": 774805,
    "milestoneStartIndex": 774805,
    "neighbors": 9,
    "packetsQueueSize": 0,
    "time": 1542182209480,
    "tips": 5013,
    "transactionsToRequest": 0
}
```

**Comment by jserv** [comment]
By the way, @marktwtn, please rebase to upstream/dev:
```
commit 569d3afa74b6df48cfffe2b8e435c4d6a19463b0
Author: Gal Rogozinski <galrogogit@gmail.com>
Date:   Wed Nov 14 13:46:54 2018 +0200
```

You can rebase on `dev-rebase` and verify first and then force push to `testing` branch.

**Comment by jserv** [comment]
@yillkid, you shall mention if vanilla IRI can reproduce or not.

**Comment by marktwtn** [comment]
I've rebased the `dev-rebase` to upsteam/dev.

The `dev-rebase` version of **IRI** never updates the latest milestone, hence the `IndexOutOfBounds` exception can not be observed.

**Comment by yillkid** [comment]
The issue never occurs since @marktwtn upgrade to the latest version (27 days). I will close this issue.
