### ISSUE TITLE
latestSolidSubtangleMilestoneIndex stuck with incorrect transaction type

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#104]
## Description
IRI `getNodeInfo` API return value `latestSolidSubtangleMilestoneIndex` stuck over 1 hour after iri launched.
## Environment
* Full-node
  * devorg
* IRI version
  * 1.5.5 
    * Vanilla
    * DLTLab dev/testing branch
* IRI launch script
```
# Run IRI service
nohup java -server \
        -Xmx6g -Xms6g -Xss1m -Xmn512m \
        -XX:+UseParallelGC \
        -XX:InitiatingHeapOccupancyPercent=0 \
        -XX:ReservedCodeCacheSize=1843200k \
        -XX:CodeCacheMinimumFreeSpace=2m \
        -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 \
        -XX:+UseCompressedOops \
        -Djava.awt.headless=true \
        -jar $IRI \
        --config config-iri-dcurl \
	-Djava.library.path="." --pearldiver-exlib dcurl \
	--remote-limit-api 'removeNeighbors, addNeighbors' --remote > nohup.out &
```
## Steps To Reproduce
Lanuch iri and wait 1 or 2 hours.
```
{
    "appName": "IRI",
    "appVersion": "1.5.5",
    "coordinatorAddress": "KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU",
    "duration": 1,
    "features": [
        "snapshotPruning",
        "dnsRefresher",
        "zeroMessageQueue",
        "RemotePOW"
    ],
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 7397476816,
    "jreMaxMemory": 8411152384,
    "jreTotalMemory": 8411152384,
    "jreVersion": "1.8.0_181",
    "latestMilestone": "WWAFLPSDKHDNUBOQNVKGMKCZPJDUVEGESTZCVZUWUGNYJTDSIHLCOIXPYTOFUGXIDRZLJUQB99MFA9999",
    "latestMilestoneIndex": 885716,
    "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestSolidSubtangleMilestoneIndex": 774805,
    "milestoneStartIndex": 774805,
    "neighbors": 9,
    "packetsQueueSize": 0,
    "time": 1542559320732,
    "tips": 125,
    "transactionsToRequest": 275
}
```
## Tracing
The IRI variable `latestSolidSubtangleMilestone` updated on function [updateLatestSolidSubtangleMilestone()](https://github.com/iotaledger/iri/blob/1a82a40a2e9ddef42e88869a2124176d665d9c89/src/main/java/com/iota/iri/MilestoneTracker.java#L268), the update condition as below:

* Get `MilestoneViewModel.latest` not null
* transactionValidator.checkSolidity(milestoneViewModel.getHash(), true)
* milestoneViewModel.index() >= latestSolidSubtangleMilestoneIndex
* ledgerValidator.updateSnapshot(milestoneViewModel)

In this case, IRI return false in the function of `transactionValidator.checkSolidity(milestoneViewModel.getHash(), true)` that  [checkSolidity](https://github.com/iotaledger/iri/blob/569d3afa74b6df48cfffe2b8e435c4d6a19463b0/src/main/java/com/iota/iri/TransactionValidator.java#L221) function check solidity of transaction (in this case transaction is latest Milestone), the condition as below will return false:

* analyzedHashes.size() >= maxProcessedTransactions
* transaction.getType() == PREFILLED_SLOT
* hashPointer == NULL
* invalid trunk and branch transactions

The root cause is the transaction type is [PREFILLED_SLOT](https://github.com/iotaledger/iri/blob/0e561af799635f6d045c372a998640c0ba506106/src/main/java/com/iota/iri/controllers/TransactionViewModel.java#L58) means that we know only hash of the tx, the rest is unknown yet: only another tx references that hash.

BUT THE TYPE IS INCORRECT!

We dump the milestone transaction hash (DIMWGWAOFCZJBOHHYQEOIALOGXDZ9WWP9PBAMBDNZCPDNLTPIUFQJMAYLWLZTZGRXNCFWQXPXAZWZ9999) and find it or get trytes by some test writen with IOTA python library:
```Python
from iota import Iota
NODE_URL="http://localhost:14265"

api = Iota(NODE_URL)
dict_txn = api.find_transactions(bundles = ['DIMWGWAOFCZJBOHHYQEOIALOGXDZ9WWP9PBAMBDNZCPDNLTPIUFQJMAYLWLZTZGRXNCFWQXPXAZWZ9999'])
list_trytes = api.get_trytes([dict_txn['hashes']])

print("The transaction hash: " + str(dict_txn['hashes']))
print("Trytes = " + str(list_trytes[0]))
```

We can get the transaction and trytes.
Output:
```
The transaction hash: [TransactionHash(b'DIMWGWAOFCZJBOHHYQEOIALOGXDZ9WWP9PBAMBDNZCPDNLTPIUFQJMAYLWLZTZGRXNCFWQXPXAZWZ9999'), TransactionHash(b'LJDHAZTPHJFABHRUDFLXYNDFIORKAJCUETHYWBYLOKJADAJVFBUQKQRMWPZYYTUCYGMQTEJDUZYPA9999')]
Trytes = {'duration': 0, 'trytes': [TryteString(b'9RHQKFHSYNLTQUHSKXDISTYOSCILFWJQLDWCRTHBPCRXMCVNIROS9FMS9JESQLMIDBRPHEBFZPGBQETBZFUS9YKCCPFCWQCZIOEWZFRBCPQHBGR9FDEQCDNAKRZDCPNXBPJDZMVOSDADONLXMU9MZQRLHQEGMTZZQKSRIHAQJKNMRQSUXLGGZXPF9BEGYEIYNGNW9FAGNYIAOGAJSIDWLCWVBAIHMUTQGVEUINGAWHXLWWUTDQRLAKJSLKMSGOZPWRYKBJRQYWDXHJQVYRQXTUYDXIXNMNAPZXS9AIPMCTFMDEGYVSFRXWJFOFUIDOOZRQFNASQXNVKTTG9PROQHQVIQNHIFPWUSSIHUOBOYJNQIWKTOUVLHHNDFJFCZZVCQSYZEWUGFMUTZQHZUGBVV9HNYNJJMX9JXWQUYCOPRLXARYYQUAXESAQHMNMH9UOVTDITQASRDWNBQO9OQHLHZCGDPWNJVHHHLYFMUZJDOGZVFKIBATBQNX9CWZMDKRZQROMMHZ9WUS9WQH9V9FFHFE9VQJUEDLSFXKVQSUKOVBNLDIFSLQWCRTKHCWBJKNBLSEUWXBPRUIZIHFMG9JPAAATHOEUTNKFECBUTR9ULOOQQEWCFYSDOPLMADXZSXVXXBBHESAWOIJTGTHTDM9UCGBHVIOZ9QYT99ETLPYNZGEINTXRVKRUMMHOQKQYRO9MDHKHCALVKEQML9LSPMCVEPCRVGCZQATSYYLRYZKNXXNVWEN9STQEGWTWBTENUMUWNZNGUCIOBTNIUQGLHAVSKPUTYZRVPAHPJRFIOHILQBOJFCKHUIYWR9YE9GGPMFDRBSOIHFONJCIDW9MBYAHLCMASTISNSJRZLNUXRBIECADHISYOMI9DADBC9OWP9XPDGJBHYEMDQVSCTNHORTEAMVDP9DHQVCLQYUOYDMQQQQRVUXLUYINWASJALCQODYKYDZXKSKDOBZ9CQORXIUNURFCZTUTKAY9MALKICWXAJAUOJDGXJDEEDWBOPAMPZLMEOPLFKMZOVNVZHIGJRK9BPNRVXLRVWXWCMTZ9OAFAMDGKQQFYZ9ZJYTD9EZGACOYHHQWJLIJYJTUMOUYYFLEOIRHOUDULBUMPJAXXVZNUNWDAWCUOPAPJUNLLUVCEYQJZHQFCMRTYC9AN9M9TAPWASEHCZRARTZKYNXCSZSQBKXPZCURYVXYEQSINLRGGFNYAPTCYBGJDAEFPYJIXKWPKJFAWZGGGUEMQ9QZXIYLCV9AVEOZXJBBHSDUAOSLQUPVYNTUCWCXZFEDWUXVGDVCZPBNWDKUSULRSX9VVJICPXYEUADFZNCM9ASPWUXQRFN9MFS9JVCZVGIMVSHSKC9OITHUMGLARSGSUK9KKCODOWGXCIBOQPQWWJRWQSDQEK9PKYCQOQT9CQCMHTWMWESXRWAUYTK9FMPCVNXVTFOGJDXE9VKVHQJHQEEWGFNLAMF9XGHNGCPHYXBIYWWWYEJCDUBWGPEVITOGXSPOJDRYUXSDMIJOC9ASNYEPNNYZYGLIAORZMG9UYELVYKNAPC9FF9OTDAEGQNCBUM9NETMZFSIKSQXLG99INCTBEFW9BYGFDQMASZIWKPIN9VYKCATZU9SYPEIC9PITWSIGDVIOMHRZFN9JJBUQEJBMSKQEESFRNZNZADVXVYBTUNQD9TS9JGQARNXPOWLYFLEHFBSVOENXLMVORWQJWRBLAEXWMTTZLRPUZTTF9QAQDIPUIVASIKGXQPZKAKKBDZCWTGFGSTOEYGLOKOOJCSSNCKZPWST9ETMNOQFEGZJM9GEBWGKKLQETLWXXNDNKAPMLALJNKSF9EKWGJNOUYAFCXYRJGW9KDFEXJJAZVQ9LKIIIJS9GJLFMZQ9BQWUCAGEG9UCKCMJGTTNZQWBTZHTGW9GZIBNSPSZUZGYLXOZB9OWTDJVBQHVXMCEZJYFNNYRGNNOCIQMSCMFQUNAX9TLGGLSNLSVOTGVZTIGJAEZWVQUUUSEKILHOTROHRATWUJDKM9GSCPNIBXCCDKYPJIFTVBVDOONOMZIULBJCODPIXAITSZURBRGWGFVQCJU9PKBZJDZSYQ9COTRTOKFWWUKTBZFUPTPYYDCAORFVLPTNV9PRNHTSVSIMHA9B99ZRLNOJRBMGBWKTJBGIMOVZXACSFIYNNTBLTJJD9BZAAAYDYSKPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU999999999999999999999999999YFDQB9999999999999999999999EAQOLZD99999999999A99999999KIMZUGLVIEXEYHDRADIADPJE9USTM9FU9PBLCZQPCNFXKHKHMXGT9HVWYHZVONVQKGDILRQYAWVTKUXYYLJDHAZTPHJFABHRUDFLXYNDFIORKAJCUETHYWBYLOKJADAJVFBUQKQRMWPZYYTUCYGMQTEJDUZYPA9999HAPPVSTGC9QVPAEUAOJYJJGXSMBEDYT9HMKONCYT9MKZITWMFMXDYKSQHVDUXDGYKOJLBYBHCRMEA99999999999999999999999999999999999999999999999999999999999UUIQLZO9HOBAONIGDMCOEQS9EY')]}
```
WE CAN GET COMPLETE TRYTES OF THIS TRANSACTION.

## Troubleshooting
The trasnaction type be set in the `Metadata` of function `preProcessReceivedData`, workflow as below:
[preProcessReceivedData()](https://github.com/iotaledger/iri/blob/b5c60d285d284222ae6819580d7b80688e0a30ff/src/main/java/com/iota/iri/network/Node.java#L238) -->
[runValidation()](https://github.com/iotaledger/iri/blob/569d3afa74b6df48cfffe2b8e435c4d6a19463b0/src/main/java/com/iota/iri/TransactionValidator.java#L162) -->
[setMetadata()](https://github.com/iotaledger/iri/blob/0e561af799635f6d045c372a998640c0ba506106/src/main/java/com/iota/iri/controllers/TransactionViewModel.java#L360)

we shell recheck the transaction metadata with [rescan](https://iota.stackexchange.com/questions/113/iri-what-are-the-differences-between-and-purposes-of-rescan-and-revalidate) parameter on iri launch. Rescan drops all the tables, except for the raw transaction trits, and re stores the transactions (refilling the metadata, address indexes etc) - this is used when a migration is needed when the DB schema changes mostly, refer the article [What are the revalidate and rescan options for](https://iri-playbook.readthedocs.io/en/master/faq.html#what-are-the-revalidate-and-rescan-options-for) for detail.

We got exception on IRI rescan the transaction tablem the full log as below
```
Logging - property 'logging-level' set to: [INFO]
11/18 22:57:39.974 [main] INFO  com.iota.iri.IRI$IRILauncher - Configuration is created using config-iri-dcurl and command line args
11/18 22:57:39.977 [main] INFO  com.iota.iri.IRI$IRILauncher - parsed the following cmd args: [--rescan, --config, config-iri-dcurl, --pearldiver-exlib, dcurl, --remote-limit-api, removeNeighbors, addNeighbors, --remote]
11/18 22:57:39.978 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI 1.5.5
11/18 22:57:49.964 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
11/18 22:57:50.328 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
11/18 22:57:50.328 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Address entries
11/18 22:57:50.376 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Bundle entries
11/18 22:57:50.502 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Approvee entries
11/18 22:57:51.435 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: ObsoleteTag entries
11/18 22:57:51.748 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Tag entries
11/18 22:57:52.036 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Milestone entries
11/18 22:57:52.043 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: StateDiff entries
11/18 22:57:52.043 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Deleting: Transaction metadata
11/18 22:57:53.720 [main] ERROR com.iota.iri.IRI$IRILauncher - Exception during IOTA node initialisation: 
java.lang.InstantiationException: com.iota.iri.model.Hash
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_181]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.modelAndIndex(RocksDBPersistenceProvider.java:245) ~[iri-1.5.5.jar:na]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.first(RocksDBPersistenceProvider.java:290) ~[iri-1.5.5.jar:na]
	at com.iota.iri.storage.Tangle.getFirst(Tangle.java:188) ~[iri-1.5.5.jar:na]
	at com.iota.iri.controllers.TransactionViewModel.first(TransactionViewModel.java:189) ~[iri-1.5.5.jar:na]
	at com.iota.iri.Iota.rescanDb(Iota.java:111) ~[iri-1.5.5.jar:na]
	at com.iota.iri.Iota.init(Iota.java:82) ~[iri-1.5.5.jar:na]
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:78) ~[iri-1.5.5.jar:na]
	at com.iota.iri.IRI.main(IRI.java:33) [iri-1.5.5.jar:na]
Caused by: java.lang.NoSuchMethodException: com.iota.iri.model.Hash.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_181]
	... 8 common frames omitted
Exception in thread "main" java.lang.InstantiationException: com.iota.iri.model.Hash
	at java.lang.Class.newInstance(Class.java:427)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.modelAndIndex(RocksDBPersistenceProvider.java:245)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.first(RocksDBPersistenceProvider.java:290)
	at com.iota.iri.storage.Tangle.getFirst(Tangle.java:188)
	at com.iota.iri.controllers.TransactionViewModel.first(TransactionViewModel.java:189)
	at com.iota.iri.Iota.rescanDb(Iota.java:111)
	at com.iota.iri.Iota.init(Iota.java:82)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:78)
	at com.iota.iri.IRI.main(IRI.java:33)
Caused by: java.lang.NoSuchMethodException: com.iota.iri.model.Hash.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 8 more
11/18 22:57:53.723 [Shutdown Hook] INFO  com.iota.iri.IRI$IRILauncher - Shutting down IOTA node, please hold tight...
11/18 22:57:59.726 [Shutdown Hook] ERROR com.iota.iri.IRI$IRILauncher - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:73) ~[iri-1.5.5.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:32) ~[iri-1.5.5.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:129) ~[iri-1.5.5.jar:na]
	at com.iota.iri.IRI$IRILauncher.lambda$shutdownHook$0(IRI.java:95) ~[iri-1.5.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```
A temporarily workround is download 3rd party IRI database and replace original one (The `latestSolidSubtangleMilestoneIndex` works again). We should move the buggy database and run with a debugging full-node.

**Comment by yillkid** [comment]
duplicate with [Crash on attempting to --rescan #371](https://github.com/iotaledger/iri/issues/371).

**Comment by yillkid** [comment]
Works fine (no need rescan) after download [3rd party IRI database](https://hackmd.io/s/ryI92GgZX), but still cannot funny-synced (`latestSolidSubtangleMilestoneIndex` grow very slowly)

**Comment by yillkid** [comment]
I close the script for restart IRI every 4 hours and wait for any issues.

**Comment by jserv** [comment]
The message `std::bad_alloc` stands for out-of-memory happening in JVM. @marktwtn, can you follow the instructions by [Minimize Java Memory Usage with the Right Garbage Collector](https://www.javacodegeeks.com/2017/11/minimize-java-memory-usage-right-garbage-collector.html) to pick up appropriate strategies with @yillkid ?

**Comment by yillkid** [comment]
@jserv I have launch IRI with `-XX:+PrintGCDetails` parameter to keep watching the GC management.

**Comment by yillkid** [comment]
Add 2 neighbors on Asia, we got lower `transactionsToRequest` in `getNodeInfo` API means we got less nonsolid request queue.

```
{
    "appName": "IRI",
    "appVersion": "1.5.5",
    "duration": 0,
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 17711000200,
    "jreMaxMemory": 19252379648,
    "jreTotalMemory": 19252379648,
    "jreVersion": "1.8.0_191",
    "latestMilestone": "SEWM9DJEHBYALDAQO9J9XPOZCMXKVPPCTPMZCAWHXGMQHDLJX9HOIQAARRZIIEZNLIYSX9KQMTRXZ9999",
    "latestMilestoneIndex": 919313,
    "latestSolidSubtangleMilestone": "SEWM9DJEHBYALDAQO9J9XPOZCMXKVPPCTPMZCAWHXGMQHDLJX9HOIQAARRZIIEZNLIYSX9KQMTRXZ9999",
    "latestSolidSubtangleMilestoneIndex": 919313,
    "milestoneStartIndex": 774805,
    "neighbors": 16,
    "packetsQueueSize": 0,
    "time": 1544629748334,
    "tips": 125,
    "transactionsToRequest": 12
}
```

**Comment by yillkid** [comment]
Total transaction counts is `3631721` after I add `-XX:+PrintGCDetails` paremater and disable the restarting script. I think it's the better workaround before we upgrade IRI to 1.6.0(local snapshot support).

```
12/12 23:50:23.033 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 17 , toReply = 0 / totalTransactions = 36317098
12/12 23:50:33.034 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 20 , toReply = 0 / totalTransactions = 36317154
12/12 23:50:43.035 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 16 , toReply = 1 / totalTransactions = 3631721
```

**Comment by yillkid** [comment]
Now all the full-node (devorg, node10) are fully synced with following conditions:
* 19~25 neighbors
* Launch IRI with -XX:+PrintGCDetails parameter (just for monitoring)

I will close this issue.

**Comment by jserv** [comment]
Use `sync'd` rather than `synced`: https://english.stackexchange.com/questions/25725/what-is-the-past-tense-of-sync
