### ISSUE TITLE
OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#105]
## Description
GC overhead limit exceeded in IRI log as below [(full-log)](https://github.com/DLTcollab/general/files/2603136/log.txt) :
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at io.undertow.util.HttpString.<init>(HttpString.java:112) ~[iri-1.5.5.jar:na]
        at io.undertow.util.HttpString.<init>(HttpString.java:106) ~[iri-1.5.5.jar:na]
        at com.iota.iri.service.API.setupResponseHeaders(API.java:1209) ~[iri-1.5.5.jar:na]
        at com.iota.iri.service.API.sendResponse(API.java:1170) ~[iri-1.5.5.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:184) ~[iri-1.5.5.jar:na]
        at com.iota.iri.service.API.access$000(API.java:59) ~[iri-1.5.5.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:141) ~[iri-1.5.5.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) ~[iri-1.5.5.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) ~[iri-1.5.5.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

## Environment
* Full-node
  * devorg
* IRI version
  * 1.5.5 
    * Vanilla
    * DLTLab dev/testing branch
* IRI launch script
```
# Run IRI service
nohup java -server \
        -Xmx6g -Xms6g -Xss1m -Xmn512m \
        -XX:+UseParallelGC \
        -XX:InitiatingHeapOccupancyPercent=0 \
        -XX:ReservedCodeCacheSize=1843200k \
        -XX:CodeCacheMinimumFreeSpace=2m \
        -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 \
        -XX:+UseCompressedOops \
        -Djava.awt.headless=true \
        -jar $IRI \
        --config config-iri-dcurl \
	-Djava.library.path="." --pearldiver-exlib dcurl \
	--remote-limit-api 'removeNeighbors, addNeighbors' --remote > nohup.out &
```

**Comment by yillkid** [comment]
Can't determine any memory leak issue from the log file, try to set Xmx (maximum memory allocation) and Xms (initial memory) from 6GB to 12GB and see.

**Comment by jserv** [comment]
We might have to change the GC implementations: https://www.javacodegeeks.com/2017/11/minimize-java-memory-usage-right-garbage-collector.html

**Comment by yillkid** [comment]
Change GC solution from `-XX:+UseParallelGC` to `-XX:+UseShenandoahGC` on `node10` and I will halve scaling step (Xms) every 72 hours.

**Comment by yillkid** [comment]
* Test shenandoah support:
`$ docker run --rm -it shipilev/openjdk-shenandoah java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -version
openjdk version "12-testing" 2019-03-19
OpenJDK Runtime Environment (build 12-testing+0-builds.shipilev.net-openjdk-shenandoah-jdk-b388-20181216-jdk-1223)
OpenJDK 64-Bit Server VM (build 12-testing+0-builds.shipilev.net-openjdk-shenandoah-jdk-b388-20181216-jdk-1223, mixed mode, sharing)`

* Launch IRI
`
$ docker run --rm -it shipilev/openjdk-shenandoah java -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -verbose:jni  -jar /home/ubuntu/mainnet-iri/iri-1.5.5-no-sync.jar
Error: Unable to access jarfile /home/ubuntu/mainnet-iri/iri-1.5.5-no-sync.jar
`

**Comment by jserv** [comment]
@yillkid, we need the corresponding investigations for IRI 1.6 or `dev` branch.

**Comment by jserv** [comment]
Close and focus on IRI 1.6.x
