### ISSUE TITLE
Devorg full-node MilestoneIndex stuck after SPAM

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#128]
There is a SPAM attack on 2019-02-13 makes 86.7 TPS

![image](https://user-images.githubusercontent.com/185872/52721336-6da3a180-2fe4-11e9-8534-bfca23a0b921.png)

That cause 1 of 2 full-synced IOTA full-node stuck, service log summary as below:

## HOST
http://node.deviceproof.org:14265

#### node10
```
{
    "appName": "IRI",
    "appVersion": "1.6.0-RELEASE",
    "coordinatorAddress": "KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU",
    "duration": 1,
    "features": [
        "snapshotPruning",
        "dnsRefresher",
        "zeroMessageQueue",
        "tipSolidification",
        "RemotePOW"
    ],
    "jreAvailableProcessors": 16,
    "jreFreeMemory": 8060986280,
    "jreMaxMemory": 19259195392,
    "jreTotalMemory": 19259195392,
    "jreVersion": "1.8.0_201",
    "lastSnapshottedMilestoneIndex": 1007399,
    "latestMilestone": "P9NFCNAOGEIJCCHNXSFQBFUMDASXZXJZTHVVWTLZRR9CSAAWAMIKUSWUSOKXZMBQGHGZEFBULJBXZ9999",
    "latestMilestoneIndex": 1007505,
    "latestSolidSubtangleMilestone": "P9NFCNAOGEIJCCHNXSFQBFUMDASXZXJZTHVVWTLZRR9CSAAWAMIKUSWUSOKXZMBQGHGZEFBULJBXZ9999",
    "latestSolidSubtangleMilestoneIndex": 1007505,
    "milestoneStartIndex": 987185,
    "neighbors": 19,
    "packetsQueueSize": 0,
    "time": 1550070345281,
    "tips": 9993,
    "transactionsToRequest": 49
}
```

#### devorg:
Both of the `latestMilestone` and `latestSolidSubtangleMilestoneIndex` stucked.
```
{
    "appName": "IRI",
    "appVersion": "1.6.0-RELEASE",
    "coordinatorAddress": "KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU",
    "duration": 0,
    "features": [
        "dnsRefresher",
        "zeroMessageQueue",
        "tipSolidification",
        "RemotePOW"
    ],
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 9553188072,
    "jreMaxMemory": 19285409792,
    "jreTotalMemory": 19285409792,
    "jreVersion": "1.8.0_191",
    "lastSnapshottedMilestoneIndex": 933210,
    "latestMilestone": "GRUHMBPYQNZNLZBDBFCXOCOCEANMRBETJOJOVLLBSLSXSRLXHYXJRANQULIYTRFHGVDACNMFGUNKA9999",
    "latestMilestoneIndex": 1007013,
    "latestSolidSubtangleMilestone": "JVVRMVCHI9YCIGWQOYIFPSWLFD9RNO9GHOEQFZPPKBRSOGIZOGKXGGHAGFKQYEUESBNUCNSEFS9DZ9999",
    "latestSolidSubtangleMilestoneIndex": 1006869,
    "milestoneStartIndex": 933211,
    "neighbors": 19,
    "packetsQueueSize": 0,
    "time": 1550070346455,
    "tips": 8092,
    "transactionsToRequest": 57
}
```

## Process
```
$ ps aux | grep iri
ubuntu   21721  0.0  0.0  16484  1012 pts/1    S+   23:13   0:00 grep --color=auto iri
testnet  32792  0.0  0.0  13220  3188 ?        Ss   Feb12   0:00 /bin/bash /home/testnet/testnet-iri/run-iri-dcurl.sh
testnet  32801  139 23.5 49352052 23275524 ?   Sl   Feb12 2757:54 java -server -Xmx18g -Xms18g -Xss1m -Xmn512m -XX:+PrintGCDetails -XX:ReservedCodeCacheSize=1843200k -XX:CodeCacheMinimumFreeSpace=200m -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -XX:+UseCompressedOops -Djava.awt.headless=true -Djava.library.path=. -jar /home/testnet/testnet-iri/iri-1.6.0-RELEASE.jar --config /home/testnet/testnet-iri/node_deviceproof_org_testnet.config --remote-limit-api removeNeighbors, addNeighbors --remote
ubuntu   40645  840 24.1 49860256 23837672 ?   Sl   Feb12 14668:29 java -server -Xmx18g -Xms18g -Xss1m -Xmn512m -XX:ReservedCodeCacheSize=1843200k -XX:CodeCacheMinimumFreeSpace=200m -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -XX:+UseCompressedOops -Djava.awt.headless=true -Djava.library.path=. -jar /home/ubuntu/iri-1.6.0-RELEASE.jar --config /home/ubuntu/config-iri-dcurl --pearldiver-exlib dcurl --remote-limit-api removeNeighbors, addNeighbors --remote
```

## IRI log
Cause various Exception after too many open files `mainnetdb/327683.log` .
```
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]: 02/07 03:26:45.867 [pool-12-thread-4] ERROR com.iota.iri.network.Node - Error accessing persistence store.
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]: org.rocksdb.RocksDBException: While open a file for appending: mainnetdb/333074.sst: Too many open files
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at org.rocksdb.RocksDB.write0(Native Method) ~[iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at org.rocksdb.RocksDB.write(RocksDB.java:806) ~[iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.saveBatch(RocksDBPersistenceProvider.java:286) ~[iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.storage.Tangle.saveBatch(Tangle.java:71) ~[iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.controllers.TransactionViewModel.store(TransactionViewModel.java:401) ~[iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.network.Node.processReceivedData(Node.java:481) [iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.network.Node.processReceivedDataFromQueue(Node.java:448) [iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at com.iota.iri.network.Node.lambda$spawnProcessReceivedThread$8(Node.java:710) [iri-1.6.0-RELEASE.jar:na]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
Feb 07 03:26:45 titan-xp run-iri-dcurl.sh[45755]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
```

[full log](https://github.com/DLTcollab/general/files/2861030/log.zip)

**Comment by yillkid** [comment]
- SPAM cause too many access request to DB files, we add 2 parameters on launch script
```
ulimit -Sn 65536
ulimit -Hn 65536
```
- SPAM cause transaction packet losting, I remove the local snapshot file `spent-addresses-db` and restart IRI service.

- We can't replace DB with other full-node or 3rd party DB files because of `devorg` is a permanode, we can't find any public resource from the community.

Now this node was synced.
```
{
    "appName": "IRI",
    "appVersion": "1.6.0-RELEASE",
    "coordinatorAddress": "KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU",
    "duration": 1,
    "features": [
        "dnsRefresher",
        "zeroMessageQueue",
        "tipSolidification",
        "RemotePOW"
    ],
    "jreAvailableProcessors": 48,
    "jreFreeMemory": 10211681464,
    "jreMaxMemory": 19271778304,
    "jreTotalMemory": 19271778304,
    "jreVersion": "1.8.0_191",
    "lastSnapshottedMilestoneIndex": 933210,
    "latestMilestone": "RPINTIDFLKM9WKYXSEGQMRBWGAUEWFWMVMOTMNIPHMB9IZMXYBRYQJOAISGHOYDOCXKVSWTTWGY999999",
    "latestMilestoneIndex": 1007752,
    "latestSolidSubtangleMilestone": "RPINTIDFLKM9WKYXSEGQMRBWGAUEWFWMVMOTMNIPHMB9IZMXYBRYQJOAISGHOYDOCXKVSWTTWGY999999",
    "latestSolidSubtangleMilestoneIndex": 1007752,
    "milestoneStartIndex": 933211,
    "neighbors": 19,
    "packetsQueueSize": 0,
    "time": 1550099730324,
    "tips": 6831,
    "transactionsToRequest": 2
}
```

**Comment by jserv** [comment]
The deploy script should reflect the changes accordingly.
