### ISSUE TITLE
Hornet database corrupted after shut down incorrectly

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#247]
Hornet launch fail after a power failure recovery.

#### Log segment:
```
Mar 23 00:55:50 hornet docker[1602]: 2020-03-23T00:55:50Z        INFO        Tangle        spent addresses Cuckoo filter contains 13309002 addresses
Mar 23 00:55:50 hornet docker[1602]: 2020-03-23T00:55:50Z        PANIC        Tangle        HORNET was not shut down correctly. Database is corrupted. Please delete the data
Mar 23 00:55:50 hornet docker[1602]: github.com/gohornet/hornet/plugins/tangle.configure
Mar 23 00:55:50 hornet docker[1602]:         /__w/hornet/hornet/plugins/tangle/plugin.go:48
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.pluginCaller
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/events.go:13
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/events.(*Event).Trigger
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/events/event.go:31
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.(*Node).configure
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.New
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.Run
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46
Mar 23 00:55:50 hornet docker[1602]: main.main
Mar 23 00:55:50 hornet docker[1602]:         /__w/hornet/hornet/main.go:35
Mar 23 00:55:50 hornet docker[1602]: runtime.main
Mar 23 00:55:50 hornet docker[1602]:         /usr/local/go/src/runtime/proc.go:203
Mar 23 00:55:50 hornet docker[1602]: panic: HORNET was not shut down correctly. Database is corrupted. Please delete the database folder and start with a new local snapshot.
Mar 23 00:55:50 hornet docker[1602]: goroutine 1 [running]:
Mar 23 00:55:50 hornet docker[1602]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ca6e0, 0x0, 0x0, 0x0)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x546
Mar 23 00:55:50 hornet docker[1602]: go.uber.org/zap.(*SugaredLogger).log(0xc0000b0018, 0xc0087d6b04, 0x0, 0x0, 0xc00399bce8, 0x1, 0x1, 0x0, 0x0, 0x0)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
Mar 23 00:55:50 hornet docker[1602]: go.uber.org/zap.(*SugaredLogger).Panic(...)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:123
Mar 23 00:55:50 hornet docker[1602]: github.com/gohornet/hornet/plugins/tangle.configure(0xc000112780)
Mar 23 00:55:50 hornet docker[1602]:         /__w/hornet/hornet/plugins/tangle/plugin.go:48 +0x615
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.pluginCaller(0xea61c0, 0x1707618, 0xc000096d80, 0x1, 0x1)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/events.go:13 +0x62
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc000188840, 0xc000096d80, 0x1, 0x1)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/events/event.go:31 +0xdb
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0001026f0, 0xc00013e000, 0xe, 0xe)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77 +0x102
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.New(0xc0004bbf48, 0x1, 0x1, 0xf3c3c0)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33 +0x124
Mar 23 00:55:50 hornet docker[1602]: github.com/iotaledger/hive.go/node.Run(0xc0004bbf48, 0x1, 0x1, 0xc000104040)
Mar 23 00:55:50 hornet docker[1602]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46 +0x3f
Mar 23 00:55:50 hornet docker[1602]: main.main()
Mar 23 00:55:50 hornet docker[1602]:         /__w/hornet/hornet/main.go:35 +0x22b
Mar 23 00:55:51 hornet systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 00:55:51 hornet systemd[1]: hornet.service: Failed with result 'exit-code'.
lines 1350850-1350891/1350891 (END)
```

**Comment by yillkid** [comment]
Still problem if just remove the snapshot file and [download a new one](https://dbfiles.iota.org/mainnet/hornet/latest-export.gz.bin).

#### Log:
```
Mar 23 03:07:30 hornet docker[3492]: panic: HORNET was not shut down correctly. Database is corrupted. Please delete the database folder and start with a new local snapshot.
Mar 23 03:07:30 hornet docker[3492]: goroutine 1 [running]:
Mar 23 03:07:30 hornet docker[3492]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000c0370, 0x0, 0x0, 0x0)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x546
Mar 23 03:07:30 hornet docker[3492]: go.uber.org/zap.(*SugaredLogger).log(0xc000010008, 0xc00025c904, 0x0, 0x0, 0xc003ae3ce8, 0x1, 0x1, 0x0, 0x0, 0x0)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
Mar 23 03:07:30 hornet docker[3492]: go.uber.org/zap.(*SugaredLogger).Panic(...)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:123
Mar 23 03:07:30 hornet docker[3492]: github.com/gohornet/hornet/plugins/tangle.configure(0xc00010c800)
Mar 23 03:07:30 hornet docker[3492]:         /__w/hornet/hornet/plugins/tangle/plugin.go:48 +0x615
Mar 23 03:07:30 hornet docker[3492]: github.com/iotaledger/hive.go/node.pluginCaller(0xea61c0, 0x1707618, 0xc000460060, 0x1, 0x1)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/events.go:13 +0x62
Mar 23 03:07:30 hornet docker[3492]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc0001807b0, 0xc000460060, 0x1, 0x1)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/events/event.go:31 +0xdb
Mar 23 03:07:30 hornet docker[3492]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0002a4f00, 0xc00029fce0, 0xe, 0xe)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77 +0x102
Mar 23 03:07:30 hornet docker[3492]: github.com/iotaledger/hive.go/node.New(0xc00029df48, 0x1, 0x1, 0xf3c3c0)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33 +0x124
Mar 23 03:07:30 hornet docker[3492]: github.com/iotaledger/hive.go/node.Run(0xc00029df48, 0x1, 0x1, 0xc000240e00)
Mar 23 03:07:30 hornet docker[3492]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46 +0x3f
Mar 23 03:07:30 hornet docker[3492]: main.main()
Mar 23 03:07:30 hornet docker[3492]:         /__w/hornet/hornet/main.go:35 +0x22b
Mar 23 03:07:30 hornet systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 03:07:30 hornet systemd[1]: hornet.service: Failed with result 'exit-code'.
```

**Comment by yillkid** [comment]
Still problem after:
1. Delete `snapshot` folder
2. Delete `mainnetdb` folder
3. Create `snapshot` folder and download [localsnapshot](https://dbfiles.iota.org/mainnet/hornet/latest-export.gz.bin) file
4. Lunch hornet

#### Log:
```
...skipping...
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Run solidity check for Milestone (1355303)...
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        WARN        Tangle        Stopped solidifier due to missing tx -> Requested missing txs (10)
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Milestone couldn't be solidified! 1355303
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Run solidity check for Milestone (1355303)...
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        WARN        Tangle        Stopped solidifier due to missing tx -> Requested missing txs (10)
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Milestone couldn't be solidified! 1355303
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Run solidity check for Milestone (1355303)...
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        WARN        Tangle        Stopped solidifier due to missing tx -> Requested missing txs (10)
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        INFO        Tangle        Milestone couldn't be solidified! 1355303
Mar 23 03:19:55 hornet docker[4049]: 2020-03-23T03:19:55Z        PANIC        Snapshot        getMilestoneApprovees: Transaction must be confirmed: UBEDVSTWIXYDWKUEGBDLVHCRR
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.getMilestoneApprovees
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:108
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.getSolidEntryPoints
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:173
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.createLocalSnapshotWithoutLocking
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:343
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.run.func2
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/plugin.go:98
Mar 23 03:19:55 hornet docker[4049]: github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/daemon/daemon.go:114
Mar 23 03:19:55 hornet docker[4049]: panic: getMilestoneApprovees: Transaction must be confirmed: UBEDVSTWIXYDWKUEGBDLVHCRRYYFWDBXSJYQTFGGBPZHHSYTUJTSQTTLRTPFRVQXOZTWFZWTBQL
Mar 23 03:19:55 hornet docker[4049]: goroutine 157 [running]:
Mar 23 03:19:55 hornet docker[4049]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00426cb00, 0x0, 0x0, 0x0)
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x546
Mar 23 03:19:55 hornet docker[4049]: go.uber.org/zap.(*SugaredLogger).log(0xc0000fc098, 0x4, 0x1087148, 0x38, 0xc01ea79808, 0x1, 0x1, 0x0, 0x0, 0x0)
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
Mar 23 03:19:55 hornet docker[4049]: go.uber.org/zap.(*SugaredLogger).Panicf(...)
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:159
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.getMilestoneApprovees(0xc00014adc4, 0xc02110ee70, 0x1, 0xc0001552c0, 0xc004dee000, 0x167, 0x
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:108 +0x63a
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.getSolidEntryPoints(0x14adf3, 0xc0001552c0, 0xc0001552c0, 0xc02155ecc0, 0x0)
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:173 +0x100
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.createLocalSnapshotWithoutLocking(0xc00014adf3, 0xc000400180, 0x1d, 0xc0001552c0, 0x0, 0x0)
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/local_snapshot.go:343 +0x2e5
Mar 23 03:19:55 hornet docker[4049]: github.com/gohornet/hornet/plugins/snapshot.run.func2(0xc0001552c0)
Mar 23 03:19:55 hornet docker[4049]:         /__w/hornet/hornet/plugins/snapshot/plugin.go:98 +0x261
Mar 23 03:19:55 hornet docker[4049]: github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1(0xc0002e2d90, 0xc000116040, 0x105bdb0, 0xe, 0xc000108250
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/daemon/daemon.go:114 +0x6d
Mar 23 03:19:55 hornet docker[4049]: created by github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker
Mar 23 03:19:55 hornet docker[4049]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/daemon/daemon.go:113 +0x129
Mar 23 03:19:55 hornet systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 03:19:55 hornet systemd[1]: hornet.service: Failed with result 'exit-code'.
```

**Comment by yillkid** [comment]
Can't re-product the issue after remove all the database folder and lunch again.
The other hand, we can not use theThangle service for latest milestone standard because it was too old.

#### Hornet
```
{
    "appName": "HORNET",
    "appVersion": "0.3.0",
    "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
    "duration": 0,
    "features": [
        "RemotePOW"
    ],
    "isSynced": true,
    "lastSnapshottedMilestoneIndex": 1354684,
    "latestMilestone": "MUCOEXEBYFATGMFRKSTNEFCSNDVPJOLRWGQTWTXJRTDBCAXOHADJTTUGJJJWTJRLOIINSW9CJ9JQ99999",
    "latestMilestoneIndex": 1355338,
    "latestSolidSubtangleMilestone": "MUCOEXEBYFATGMFRKSTNEFCSNDVPJOLRWGQTWTXJRTDBCAXOHADJTTUGJJJWTJRLOIINSW9CJ9JQ99999",
    "latestSolidSubtangleMilestoneIndex": 1355338,
    "milestoneStartIndex": 1354684,
    "neighbors": 4,
    "time": 1584936305000,
    "tips": 0,
    "transactionsToRequest": 0
}
```

#### IOTA nodes
![image](https://user-images.githubusercontent.com/185872/77280191-9e352f00-6cfe-11ea-97d9-ac8ccadeaf32.png)

#### theTangle
![image](https://user-images.githubusercontent.com/185872/77280202-a8efc400-6cfe-11ea-8e18-7798d5524076.png)

#### Discord
![image](https://user-images.githubusercontent.com/185872/77280230-bb69fd80-6cfe-11ea-80a8-c3dce76aea9d.png)

**Comment by yillkid** [comment]
#### Conclusion
1. Hornet will lunch fail after the service shutdown incorrect.
2. It would remove all the database folder and download the latest local snapshot for recovery.
3. We still should backup the `mainnetdb` period if we want to use hornet as permanode. 
4. Use [IOTA nodea](https://iota-nodes.net/) as latest milestone standard.

**Comment by yillkid** [comment]
Occur again
```
Mar 23 05:13:01 hornet docker[4746]: panic: HORNET was not shut down correctly. Database is corrupted. Please delete the database folder and start with a new local snapshot.
Mar 23 05:13:01 hornet docker[4746]: goroutine 1 [running]:
Mar 23 05:13:01 hornet docker[4746]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ca420, 0x0, 0x0, 0x0)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x546
Mar 23 05:13:01 hornet docker[4746]: go.uber.org/zap.(*SugaredLogger).log(0xc000108030, 0xc0041a5804, 0x0, 0x0, 0xc0041d3ce8, 0x1, 0x1, 0x0, 0x0, 0x0)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
Mar 23 05:13:01 hornet docker[4746]: go.uber.org/zap.(*SugaredLogger).Panic(...)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:123
Mar 23 05:13:01 hornet docker[4746]: github.com/gohornet/hornet/plugins/tangle.configure(0xc0000747c0)
Mar 23 05:13:01 hornet docker[4746]:         /__w/hornet/hornet/plugins/tangle/plugin.go:48 +0x615
Mar 23 05:13:01 hornet docker[4746]: github.com/iotaledger/hive.go/node.pluginCaller(0xea61c0, 0x1707618, 0xc0003ec0d0, 0x1, 0x1)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/events.go:13 +0x62
Mar 23 05:13:01 hornet docker[4746]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc000182810, 0xc0003ec0d0, 0x1, 0x1)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/events/event.go:31 +0xdb
Mar 23 05:13:01 hornet docker[4746]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0003e09f0, 0xc0003e8150, 0xe, 0xe)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:77 +0x102
Mar 23 05:13:01 hornet docker[4746]: github.com/iotaledger/hive.go/node.New(0xc00028df48, 0x1, 0x1, 0xf3c3c0)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:33 +0x124
Mar 23 05:13:01 hornet docker[4746]: github.com/iotaledger/hive.go/node.Run(0xc00028df48, 0x1, 0x1, 0xc0001050a0)
Mar 23 05:13:01 hornet docker[4746]:         /go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200107205115-986a54f82a30/node/node.go:46 +0x3f
Mar 23 05:13:01 hornet docker[4746]: main.main()
Mar 23 05:13:01 hornet docker[4746]:         /__w/hornet/hornet/main.go:35 +0x22b
Mar 23 05:13:01 hornet systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 05:13:01 hornet systemd[1]: hornet.service: Failed with result 'exit-code'.
```

**Comment by yillkid** [comment]
> Alex2020/03/12
it is not importing the snapshots you are using, it is when your node is creating a local snapshot that this happens. So please disable local snapshots until the next release

#### Disable local snapshot
```
  "localsnapshots": {
    "enabled": false,
    "depth": 50,
    "intervalsynced": 50,
    "intervalunsynced": 1000,
    "path": "snapshot/latest-export.gz.bin"
   },
```

**Comment by yillkid** [comment]
Everything is fine after disable snapshot.
```
systemctl status hornet
● hornet.service - Hornet IOTA
   Loaded: loaded (/etc/systemd/system/hornet.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-03-24 03:11:47 UTC; 1h 45min ago
  Process: 8085 ExecStartPre=/bin/bash -c /usr/bin/docker rm hornet || /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 8110 (docker)
    Tasks: 10 (limit: 2317)
   CGroup: /system.slice/hornet.service
           └─8110 /usr/bin/docker run --name hornet --net=host --user=39999 --cap-drop=ALL -v /etc/localtime:/etc/localtime:ro,Z -v /var/lib/hornet/mainnetdb:/app/mainnetdb:

Mar 24 04:57:36 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14970, bndlsValidated: 113107, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:37 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14970, bndlsValidated: 113112, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:38 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14971, bndlsValidated: 113117, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:39 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14973, bndlsValidated: 113126, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:40 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14974, bndlsValidated: 113130, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:41 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14974, bndlsValidated: 113138, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:42 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14975, bndlsValidated: 113145, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:43 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14976, bndlsValidated: 113148, txReqs(Tx/Rx): 86243/62
Mar 24 04:57:44 hornet docker[8110]: EOF
Mar 24 04:57:44 hornet docker[8110]: reqQ: 00000, reqQMs: 0, processor: 00000, LSMI/LMI: 1356478/1356478, addrsMarked: 14983, bndlsValidated: 113164, txReqs(Tx/Rx): 86243/62
```
