### ISSUE TITLE
No space left on node10

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#253]
## Journalctl log
```
May 04 02:58:58 tangle systemd[1]: Started IOTA FullNode.
May 04 02:58:59 tangle iri[27763]: Logging - property 'logging-level' set to: [INFO]
May 04 02:58:59 tangle iri[27763]: 05/04 02:58:59.613 [main] INFO  IRI$IRILauncher:192 - Configuration is created using iri.ini and command line args
May 04 02:58:59 tangle iri[27763]: 05/04 02:58:59.615 [main] INFO  IRI$IRILauncher:193 - parsed the following cmd args: [-c, /var/lib/iri/iri.ini, --port, 14265, --neighboring-socket-address
May 04 02:58:59 tangle iri[27763]: 05/04 02:58:59.616 [main] INFO  IRI$IRILauncher:122 - Welcome to IRI 1.8.5-COACH
May 04 02:58:59 tangle iri[27763]: WARNING: An illegal reflective access operation has occurred
May 04 02:58:59 tangle iri[27763]: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/var/lib/iri/target/iri-1.8.5-COACH.jar) to method java.l
May 04 02:58:59 tangle iri[27763]: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
May 04 02:58:59 tangle iri[27763]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
May 04 02:58:59 tangle iri[27763]: WARNING: All illegal access operations will be denied in a future release
May 04 02:59:00 tangle iri[27763]: Warning: Nashorn engine is planned to be removed from a future JDK release
May 04 02:59:00 tangle iri[27763]: 05/04 02:59:00.189 [main] INFO  PearlDiver:59 - No external library for PearlDiver
May 04 02:59:01 tangle iri[27763]: 05/04 02:59:01.841 [main] INFO  SnapshotProviderImpl:227 - resumed from local snapshot #1384219 ...
May 04 02:59:01 tangle iri[27763]: 05/04 02:59:01.956 [main] INFO  RocksDBPersistenceProvider:87 - Initializing Database on spent-addresses-db
May 04 02:59:01 tangle iri[27763]: Exception in thread "main" java.lang.ExceptionInInitializerError
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:437)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:88)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.service.spentaddresses.impl.SpentAddressesProviderImpl.init(SpentAddressesProviderImpl.java:58)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.Iota.initDependencies(Iota.java:150)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.Iota.init(Iota.java:169)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.IRI$IRILauncher.main(IRI.java:135)
May 04 02:59:01 tangle iri[27763]:         at com.iota.iri.IRI.main(IRI.java:64)
May 04 02:59:01 tangle iri[27763]: Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared libraryjava.io.IOException: No space left on device
May 04 02:59:01 tangle iri[27763]:         at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
May 04 02:59:01 tangle iri[27763]:         at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
May 04 02:59:01 tangle iri[27763]:         ... 7 more
May 04 02:59:01 tangle iri[27763]: 05/04 02:59:01.964 [Shutdown Hook] INFO  IRI$IRILauncher:152 - Shutting down IOTA node, please hold tight...
May 04 02:59:01 tangle iri[27763]: 05/04 02:59:01.967 [Shutdown Hook] INFO  Tangle:74 - Shutting down Tangle Persistence Providers...
May 04 02:59:01 tangle iri[27763]: 05/04 02:59:01.968 [Shutdown Hook] INFO  Tangle:77 - Shutting down Tangle MessageQueue Providers...
May 04 02:59:02 tangle systemd[1]: iri.service: Main process exited, code=exited, status=1/FAILURE
May 04 02:59:02 tangle systemd[1]: iri.service: Failed with result 'exit-code'.
```

**Comment by yillkid** [comment]
Add a new storage by LVM
```
root@tangle:~# fdisk -l
Disk /dev/loop0: 93.8 MiB, 98336768 bytes, 192064 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 93.9 MiB, 98484224 bytes, 192352 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes




GPT PMBR size mismatch (419430399 != 524287999) will be corrected by w(rite).
Disk /dev/sda: 250 GiB, 268435456000 bytes, 524288000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 5BD7AC69-033A-42B0-BC2E-D5E8C8DD1B3A

Device       Start       End   Sectors  Size Type
/dev/sda1     2048      4095      2048    1M BIOS boot
/dev/sda2     4096   2101247   2097152    1G Linux filesystem
/dev/sda3  2101248 419428351 417327104  199G Linux filesystem


Disk /dev/sdb: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7efe0a36

Device     Boot Start       End   Sectors Size Id Type
/dev/sdb1        2048 104857599 104855552  50G 8e Linux LVM


Disk /dev/mapper/ubuntu--vg-ubuntu--lv: 249 GiB, 267353325568 bytes, 522174464 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

- TODO:
  - Format the partition
  - Testing IRI

**Comment by yillkid** [comment]
Works and syncing.

```
{
    "appName": "IRI",
    "appVersion": "1.8.5-COACH",
    "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
    "duration": 1,
    "features": [
        "dnsRefresher",
        "zeroMessageQueue",
        "RemotePOW"
    ],
    "jreAvailableProcessors": 4,
    "jreFreeMemory": 391178128,
    "jreMaxMemory": 4294967296,
    "jreTotalMemory": 1312817152,
    "jreVersion": "11.0.7",
    "lastSnapshottedMilestoneIndex": 1384219,
    "latestMilestone": "TBOPHAKGXKWUMRAYZKJUSINARPNBVLZ9W9ALVCNSRNHDYMUEBTOEGHKVZWKVNWJY9BOOSYYIORUOZ9999",
    "latestMilestoneIndex": 1394325,
    "latestSolidSubtangleMilestone": "HIWXZYSATMOFGPMXNYBZZJW9UFAGPLUZGDTV9VNONGZYKBCCBWOKJKSNDAGJROJRXWESYVPQVMYSA9999",
    "latestSolidSubtangleMilestoneIndex": 1384219,
    "milestoneStartIndex": 1050381,
    "neighbors": 4,
    "packetsQueueSize": 0,
    "time": 1589173264560,
    "tips": 16,
    "transactionsToRequest": 0
}
```
