### ISSUE TITLE
Node10: panic: runtime error: index out of range [7] with length 0

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#270]
Node10 HORNET get `panic: runtime error: index out of range [7] with length 0` error message after recovered from a power failure.

## System status
```
● hornet.service - Hornet IOTA
   Loaded: loaded (/etc/systemd/system/hornet.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-08-17 02:07:08 UTC; 3h 37min ago
  Process: 2236 ExecStart=/usr/bin/docker run --name hornet --net=host --user=39999 --cap-drop=ALL -v /etc/localtime:/etc/localtime:ro,Z -v /var/lib/hornet/mainnetdb:/app/mainnetdb:rw,Z -v /
  Process: 2019 ExecStartPre=/bin/bash -c /usr/bin/docker rm hornet || /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 2236 (code=exited, status=2)

Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0001d1e60, 0xc0000d0b00, 0x15, 0x16)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:93 +0xf6
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.New(0xc0002a1e98, 0x1, 0x1, 0x109de00)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:38 +0x153
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.Run(0xc0002a1e98, 0x1, 0x1, 0xc00000f6c0)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:51 +0x3f
Aug 17 02:07:08 node10 docker[2236]: main.main()
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/main.go:67 +0x245
Aug 17 02:07:08 node10 systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 02:07:08 node10 systemd[1]: hornet.service: Failed with result 'exit-code'.
```

## Log segment:

```
Aug 17 02:04:55 node10 docker[2236]: SnapshotInfo:
Aug 17 02:04:55 node10 docker[2236]:         CooAddr: EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9
Aug 17 02:04:55 node10 docker[2236]:         SnapshotIndex: 1527673 (VJFGJDYKYFNTEBDPDNZOPXDZCUEAIKFSHMWYDWGXBNSITXOEUCPI9HBUTJABFOHWUIQIBAAHVELNZ9999)
Aug 17 02:04:55 node10 docker[2236]:         EntryPointIndex: 1512690
Aug 17 02:04:55 node10 docker[2236]:         PruningIndex: 1512690
Aug 17 02:04:55 node10 docker[2236]:         Timestamp: 2020-08-13 12:30:14 +0000 UTC
Aug 17 02:04:55 node10 docker[2236]:         SpentAddressesEnabled: true
Aug 17 02:04:55 node10 docker[2236]: 2020-08-17T02:04:55Z        INFO        Node        Loading Plugin: Tangle ... done
Aug 17 02:04:55 node10 docker[2236]: 2020-08-17T02:04:55Z        INFO        Node        Loading Plugin: Peering ... done
Aug 17 02:04:55 node10 docker[2236]: 2020-08-17T02:04:55Z        INFO        Node        Loading Plugin: WarpSync ... done
Aug 17 02:04:55 node10 docker[2236]: 2020-08-17T02:04:55Z        INFO        Node        Loading Plugin: Tip-Sel ... done
Aug 17 02:04:55 node10 docker[2236]: 2020-08-17T02:04:55Z        INFO        Node        Loading Plugin: Metrics ... done
Aug 17 02:07:08 node10 docker[2236]: panic: runtime error: index out of range [7] with length 0
Aug 17 02:07:08 node10 docker[2236]: goroutine 1 [running]:
Aug 17 02:07:08 node10 docker[2236]: encoding/binary.littleEndian.Uint64(...)
Aug 17 02:07:08 node10 docker[2236]:         /usr/local/go/src/encoding/binary/binary.go:77
Aug 17 02:07:08 node10 docker[2236]: github.com/gohornet/hornet/pkg/model/tangle.balanceFromBytes(...)
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:71
Aug 17 02:07:08 node10 docker[2236]: github.com/gohornet/hornet/pkg/model/tangle.GetLedgerStateForLSMIWithoutLocking.func1(0xc0001cc000, 0x62, 0x62, 0x2a0ac80, 0x0, 0x0, 0x0)
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:347 +0x116
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/kvstore/bolt.boltStore.iterate.func1(0xc0002390a0, 0xc0001dea00, 0xc0002390a0)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/kvstore/bolt/bolt.go:67 +0x498
Aug 17 02:07:08 node10 docker[2236]: go.etcd.io/bbolt.(*DB).View(0xc000277800, 0xc000ca77f8, 0x0, 0x0)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:725 +0x8e
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/kvstore/bolt.boltStore.iterate(0xc000277800, 0xc0004b21f3, 0x1, 0x1, 0x2a0a7e0, 0x0, 0x0, 0x1, 0xc00000fa60, 0x1172601, ...
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/kvstore/bolt/bolt.go:42 +0xd3
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/kvstore/bolt.(*boltStore).Iterate(0xc0004942a0, 0x2a0a7e0, 0x0, 0x0, 0xc00000fa60, 0x0, 0x31)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/kvstore/bolt/bolt.go:76 +0x80
Aug 17 02:07:08 node10 docker[2236]: github.com/gohornet/hornet/pkg/model/tangle.GetLedgerStateForLSMIWithoutLocking(0x0, 0xc00048aa00, 0xf3, 0xf3, 0xc0001c0b80)
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:339 +0xe2
Aug 17 02:07:08 node10 docker[2236]: github.com/gohornet/hornet/pkg/model/tangle.GetLedgerStateForLSMI(0x0, 0x0, 0x0, 0x0, 0x0)
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:376 +0x82
Aug 17 02:07:08 node10 docker[2236]: github.com/gohornet/hornet/plugins/snapshot.configure(0xc000071540)
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/plugins/snapshot/plugin.go:112 +0xb12
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.pluginCaller(0xfedda0, 0x20064b0, 0xc00023cc40, 0x1, 0x1)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/events.go:14 +0x62
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc00009bb60, 0xc00023cc40, 0x1, 0x1)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/events/event.go:32 +0x10d
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.(*Node).configure(0xc0001d1e60, 0xc0000d0b00, 0x15, 0x16)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:93 +0xf6
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.New(0xc0002a1e98, 0x1, 0x1, 0x109de00)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:38 +0x153
Aug 17 02:07:08 node10 docker[2236]: github.com/iotaledger/hive.go/node.Run(0xc0002a1e98, 0x1, 0x1, 0xc00000f6c0)
Aug 17 02:07:08 node10 docker[2236]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/node/node.go:51 +0x3f
Aug 17 02:07:08 node10 docker[2236]: main.main()
Aug 17 02:07:08 node10 docker[2236]:         /__w/hornet/hornet/main.go:67 +0x245
Aug 17 02:07:08 node10 systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 02:07:08 node10 systemd[1]: hornet.service: Failed with result 'exit-code'.
```

**Comment by yillkid** [comment]
Remove database and download the new local snapshot file.

```json
{
    "appName": "HORNET",
    "appVersion": "0.4.2",
    "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
    "duration": 0,
    "features": [
        "RemotePOW",
        "WereAddressesSpentFrom"
    ],
    "isSynced": true,
    "lastSnapshottedMilestoneIndex": 1534287,
    "latestMilestone": "GPSTAJSV9MQAIACZNXPAHRWEXQTHJOGKUDZXPQNYML9DKGTLWFEGFETAJAAPQAZQWXICJXKLFGXAZ9999",
    "latestMilestoneIndex": 1534337,
    "latestSolidSubtangleMilestone": "GPSTAJSV9MQAIACZNXPAHRWEXQTHJOGKUDZXPQNYML9DKGTLWFEGFETAJAAPQAZQWXICJXKLFGXAZ9999",
    "latestSolidSubtangleMilestoneIndex": 1534337,
    "milestoneStartIndex": 1533942,
    "neighbors": 1,
    "time": 1597668813000,
    "tips": 0,
    "transactionsToRequest": 0
}
```
