### ISSUE TITLE
Iotavisualization can't run.

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#54]
In gitlab by @proof.K on Mar 13, 2018, 14:33

use "npm run dev-server"

the error log:

0 info it worked if it ends with ok

1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev-server' ]

2 info using npm@5.6.0

3 info using node@v8.9.4

4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]

5 info lifecycle jsdemo@1.0.0~predev-server: jsdemo@1.0.0

6 info lifecycle jsdemo@1.0.0~dev-server: jsdemo@1.0.0

7 verbose lifecycle jsdemo@1.0.0~dev-server: unsafe-perm in lifecycle true

8 verbose lifecycle jsdemo@1.0.0~dev-server: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/don/iotavisualization/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

9 verbose lifecycle jsdemo@1.0.0~dev-server: CWD: /home/don/iotavisualization

10 silly lifecycle jsdemo@1.0.0~dev-server: Args: [ '-c', 'webpack-dev-server' ]

11 silly lifecycle jsdemo@1.0.0~dev-server: Returned: code: 1  signal: null

12 info lifecycle jsdemo@1.0.0~dev-server: Failed to exec dev-server script

13 verbose stack Error: jsdemo@1.0.0 dev-server: `webpack-dev-server`

13 verbose stack Exit status 1

13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

14 verbose pkgid jsdemo@1.0.0

15 verbose cwd /home/don/iotavisualization

16 verbose Linux 4.13.0-25-generic

17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev-server"

18 verbose node v8.9.4
19 verbose npm  v5.6.0

20 error code ELIFECYCLE
21 error errno 1
22 error jsdemo@1.0.0 dev-server: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the jsdemo@1.0.0 dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 13, 2018, 14:35

changed the description

**Comment by yillkid** [comment]
In gitlab by @proof.K on Mar 13, 2018, 15:13

closed
