### ISSUE TITLE
Base: Compile IRI into native build via GraalVM

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#67]
In gitlab by @chenwei on Apr 26, 2018, 13:16

The article [Top 10 Things To Do With GraalVM](https://medium.com/graalvm/graalvm-ten-things-12d9111f307d) illustrated that Java programs can be compiled to a native library for C program to load.

GraalVM lets you take Java library, either off-the-shelf or one you’ve written yourself, and compile it to a standalone native library for use from other native languages. As with native compilation before, they don’t require a JVM to run, that is suitable for deployment purpose.

**Comment by yillkid** [comment]
In gitlab by @chenwei on Apr 26, 2018, 13:16

changed the description

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:24

changed title from **Base: Compile IRI to a native library** to **Base: Compile IRI to a native library{+ via GraalVM+}**

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:24

changed the description

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:26

changed the description

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:46

Graal is like a compiler library and it can be used in many different ways. One of those is to compile ahead-of-time (AOT), to a native executable image, instead of compiling just-in-time at runtime. This is similar to how a conventional compiler like GCC works.

However, while using `native-image` to generate AOT images, the following error message were shown:
```
   classlist:   1,789.95 ms
       (cap):   1,552.51 ms
       setup:   2,613.85 ms
    analysis:   9,776.56 ms
error: unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.ClassLoader.getParent() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
```

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:49

Once the option `-H:+ReportUnsupportedElementsAtRuntime` was appended to `native-image` (shipped by Community Edition, fully open sourced), ELF `iri-1.4.2.4` was generated as expected, but it failed to proceed:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_IRI_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.IllegalArgumentException: Provider org.ini4j.spi.IniParser could not be instantiated: java.lang.InstantiationException: Type `org.ini4j.spi.IniParser` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
```

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 06:53

[Substrate VM Java Limitations](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md) denotes that Substrate VM does not support all features of Java to keep the implementation small and concise, and also to allow aggressive ahead-of-time optimizations. The above `native-image` failure resulted from the fact that Java Reflection is partially supported by GraalVM and dynamic class-loading just doesn’t work with GraalVM, either.

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 07:33

I just switched to GraalVM Enterprise Edition (graalvm-ee) and executed `native-image` again:
```shell
$ native-image --no-server -jar iri-1.4.2.4.jar 
   classlist:   1,850.64 ms
       (cap):   1,467.14 ms
       setup:   2,853.05 ms
05/23 07:26:35.622 [ForkJoinPool-3-worker-10] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
05/23 07:26:36.160 [ForkJoinPool-3-worker-1] INFO  org.xnio - XNIO version 3.3.6.Final
05/23 07:26:36.748 [ForkJoinPool-3-worker-30] DEBUG io.undertow - JDK9 ALPN not supported
java.lang.NoSuchMethodException: javax.net.ssl.SSLParameters.setApplicationProtocols([Ljava.lang.String;)
```

**Comment by yillkid** [comment]
In gitlab by @jserv on May 23, 2018, 12:17

Insightful note: [Instant Netty Startup using GraalVM Native Image Generation](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692)

**Comment by jserv** [comment]
GraalVM developer chatroom on `native-image`: https://gitter.im/graalvm/native-image

**Comment by jserv** [comment]
This task was activated because of the active development of GraalVM.
I have tried IRI-1.8.0 along with GraalVM 19.1.1. The configuration file is not functioned yet:
```
$ ./iri-1.8.0-RELEASE -c config-iri.ini 
Logging - property 'logging-level' set to: [INFO]
Aug 08, 2019 9:52:08 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
21:52:08.526 [main] ERROR com.iota.iri.IRI$IRILauncher - There was a problem reading configuration from file: (was java.lang.UnsupportedOperationException) (through reference chain: com.iota.iri.conf.MainnetConfig["NEIGHBORS"])
21:52:08.526 [main] DEBUG com.iota.iri.IRI$IRILauncher - 
java.lang.IllegalArgumentException: (was java.lang.UnsupportedOperationException) (through reference chain: com.iota.iri.conf.MainnetConfig["NEIGHBORS"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3751)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669)
	at com.iota.iri.conf.ConfigFactory.createFromFile(ConfigFactory.java:72)
	at com.iota.iri.IRI$IRILauncher.createConfiguration(IRI.java:161)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:116)
	at com.iota.iri.IRI.main(IRI.java:61)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: com.iota.iri.conf.MainnetConfig["NEIGHBORS"])
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3746)
	... 5 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.deserializeAndSet(SetterlessProperty.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 7 common frames omitted
```

**Comment by jserv** [comment]
If no configuration file is assigned, IRI would take the default values and execute with native-image build:
```
$ ./iri-1.8.0-RELEASE 
Logging - property 'logging-level' set to: [INFO]
00:55:00.799 [main] INFO com.iota.iri.IRI$IRILauncher - Configuration is created using command line args only
00:55:00.799 [main] INFO com.iota.iri.IRI$IRILauncher - parsed the following cmd args: []
00:55:00.799 [main] INFO com.iota.iri.IRI$IRILauncher - Welcome to IRI 1.8.0-RELEASE
...
00:55:49.741 [Local Snapshots Monitor] INFO com.iota.iri.utils.thread.ThreadUtils - Local Snapshots Monitor [STARTED]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.undertow.servlet.api.ServletInfo.<init>(ServletInfo.java:85)
	at io.undertow.servlet.Servlets.servlet(Servlets.java:102)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:66)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:104)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:121)
	at com.iota.iri.service.restserver.resteasy.RestEasy.init(RestEasy.java:135)
	at com.iota.iri.service.API.init(API.java:204)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:130)
	at com.iota.iri.IRI.main(IRI.java:61)
Caused by: java.lang.IllegalArgumentException: Invalid bundle interface io.undertow.servlet.UndertowServletMessages (implementation not found)
	at org.jboss.logging.Messages$1.run(Messages.java:83)
	at java.security.AccessController.doPrivileged(AccessController.java:68)
	at org.jboss.logging.Messages.getBundle(Messages.java:58)
	at org.jboss.logging.Messages.getBundle(Messages.java:46)
	at io.undertow.servlet.UndertowServletMessages.<clinit>(UndertowServletMessages.java:45)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 10 more
```

**Comment by jserv** [comment]
Right now, it is usable.
Given `config-iri.ini`:
```
[IRI]
PORT = 1999
UDP_RECEIVER_PORT = 1998
DEBUG = true
NEIGHBORS = "tcp://wiix.qal.io:15600"
LOCAL_SNAPSHOTS_ENABLED = false
API_HOST = 0.0.0.0
REMOTE_LIMIT_API = "addNeighbors removeNeighbors"
```

Launch native-image build:
```
$ ./iri-1.8.0-RELEASE -c config-iri.ini 
Logging - property 'logging-level' set to: [INFO]
08/09 13:53:21.468 [main] INFO  IRI$IRILauncher:183 - Configuration is created using config-iri.ini and command line args
08/09 13:53:21.471 [main] INFO  IRI$IRILauncher:184 - parsed the following cmd args: [-c, config-iri.ini]
...
08/09 13:50:48.755 [main] INFO  IRI$IRILauncher:131 - IOTA Node initialised correctly.
08/09 13:50:55.778 [Tips Requester] INFO  TipsRequesterImpl:86 - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 0
```

I am about to prepare the instructions to generate GraalVM-based IRI native images for @marktwtn 's reference. Then, we might think about moving into `IRI-1.8.0-COACH`.

**Comment by jserv** [comment]
Fatal runtime exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.undertow.servlet.api.ServletInfo.<init>(ServletInfo.java:85)
	at io.undertow.servlet.Servlets.servlet(Servlets.java:102)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:66)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:104)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.undertowDeployment(UndertowJaxrsServer.java:121)
	at com.iota.iri.service.restserver.resteasy.RestEasy.init(RestEasy.java:135)
	at com.iota.iri.service.API.init(API.java:204)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:130)
	at com.iota.iri.IRI.main(IRI.java:61)
Caused by: java.lang.IllegalArgumentException: Invalid bundle interface io.undertow.servlet.UndertowServletMessages (implementation not found)
	at org.jboss.logging.Messages$1.run(Messages.java:83)
	at java.security.AccessController.doPrivileged(AccessController.java:68)
	at org.jboss.logging.Messages.getBundle(Messages.java:58)
	at org.jboss.logging.Messages.getBundle(Messages.java:46)
	at io.undertow.servlet.UndertowServletMessages.<clinit>(UndertowServletMessages.java:45)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 10 more
```

**Comment by jserv** [comment]
After implementing several in directory `src/main/java/com/iota/iri/runtime/graal/`, native-image built IRI now work partially:
```
07:10:25.047 [main] INFO com.iota.iri.service.milestone.MilestoneSolidifier - Starting [Milestone Solidifier] (starts in 0ms / runs every 500ms) ...
07:10:25.047 [main] INFO com.iota.iri.utils.thread.ThreadUtils - Starting Thread: Local Snapshots Monitor ...
07:10:25.047 [main] DEBUG com.iota.iri.service.restserver.resteasy.RestEasy - Binding JSON-REST API Undertow server on localhost:1999
07:10:25.047 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
07:10:25.048 [main] DEBUG io.undertow - starting undertow server io.undertow.Undertow@7f86792e69a0
07:10:25.048 [main] INFO org.xnio - XNIO version 3.7.2.Final
07:10:25.049 [main] INFO org.xnio.nio - XNIO NIO Implementation Version 3.7.2.Final
```

**Comment by jserv** [comment]
Package upgrade:
* xnio: 3.7.3.Final
* undertow: 2.0.25.Final
* jboss-threads: Git HEAD + unsafe hacks

Log:
```
05:11:47.064 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
05:11:47.064 [main] DEBUG io.undertow - starting undertow server io.undertow.Undertow@7f430dbe6778
05:11:47.065 [main] INFO org.xnio - XNIO version 3.7.3.Final
05:11:47.065 [main] INFO org.xnio.nio - XNIO NIO Implementation Version 3.7.3.Final
05:11:47.067 [XNIO-1 I/O-1] DEBUG org.xnio.nio - Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@7f42f2b87578
...
05:11:47.086 [main] DEBUG io.undertow - Configuring listener with protocol HTTP for interface localhost and port 1999
05:11:47.087 [main] DEBUG io.undertow.session - Setting default session timeout to 1800
05:11:47.087 [main] DEBUG io.undertow.session - Registered session listener io.undertow.servlet.core.SessionListenerBridge@7f42244203c8
05:11:47.088 [main] ERROR com.iota.iri.IRI$IRILauncher - Exception during IOTA node initialisation: 
java.lang.RuntimeException: javax.servlet.ServletException: UT010013: Could not instantiate ResteasyServlet
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.deploy(UndertowJaxrsServer.java:276)
	at com.iota.iri.service.restserver.resteasy.RestEasy.start(RestEasy.java:201)
	at com.iota.iri.service.API.init(API.java:205)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:130)
	at com.iota.iri.IRI.main(IRI.java:61)
Caused by: javax.servlet.ServletException: UT010013: Could not instantiate ResteasyServlet
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:300)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:143)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:585)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:556)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:598)
	at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.deploy(UndertowJaxrsServer.java:272)
	... 4 common frames omitted
```

**Comment by jserv** [comment]
Switched to GraalVM 19.3.0 and resolved pending issues.
