### ISSUE TITLE
mam.client.js is not working

### ISSUE THREAD

**Issue by yillkid** [DLTcollab/general#8]
In gitlab by @root on Dec 14, 2017, 10:06

*Created by: HexRabbit*

[mam.client.js](https://github.com/iotaledger/mam.client.js/)

There's a bug in MAM.create()
```js
bundle.addEntry(signatureFragments.length, address, value, tag, timestamp);
                                       ^
TypeError: Cannot read property 'length' of null
    at new create (/home/hexshift/mam.client.js/lib/mam.js:103:40)
    at Object.<anonymous> (/home/hexshift/mam.client.js/examples/post.js:25:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

Action items:
1. File bug in upstream GitHub;
2. Track upstream issues and participate in corresponding discussions;

**Comment by yillkid** [comment]
In gitlab by @root on Dec 29, 2017, 10:43

*Created by: HexRabbit*

Still no respond from developer. 

I found an another usable repo from l3wi, **but the implementation is different**.

(same as the description on medium)

<https://github.com/l3wi/mam.client.js/>

**Comment by yillkid** [comment]
In gitlab by @jserv on Feb 2, 2018, 18:09

assigned to @HexRabbit

**Comment by yillkid** [comment]
In gitlab by @jserv on Feb 2, 2018, 18:10

@HexRabbit, Close this ticket after evaluation.

**Comment by yillkid** [comment]
In gitlab by @HexRabbit on Feb 6, 2018, 16:54

iotaledger has forked the l3wi's MAM repo and deleted the old one.

This version works properly.

**Comment by yillkid** [comment]
In gitlab by @HexRabbit on Feb 6, 2018, 16:54

closed
