### ISSUE TITLE
Test XDK2MAM

### ISSUE THREAD

**Issue by csielee** [DLTcollab/general#92]
[XDK2MAM](http://xdk2mam.io/)
Open source code for the Bosch XDK 110 to interact with Tangle through MAM

- Transfer data of XDK with IOTA MAM.
- Expect querying data at MAM Explorer.

Note : [Test XDK2MAM](https://hackmd.io/s/SJ8ugCdDm)

**Comment by csielee** [comment]
Successfully get root address and XDK data
But find error : MAM attach time out

environment : 

```javascript
let iota = new IOTA({
  'host' : 'https://node.deviceproof.org',
  'port': '443'
});
```

error message:

```
failed to attach message: 
 Error: Invalid Response: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

    at Object.invalidResponse (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
    at makeRequest.prepareResult (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/iota.lib.js/lib/utils/makeRequest.js:285:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/grass0756110/xdk/xdk2mam/http/xdk2mam-nodejs/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

```

**Comment by csielee** [comment]
Successfully upload XDK data with MAM

Solve is changing iri node

```
let iota = new IOTA({
  'host' : 'https://potato.iotasalad.org',
  'port': '14265'
});
```

[MAM explorer for this test](https://mam.tangle.army/fetch?address=VCYLPQQ9HPO9KEYU9INYPGYMVVHL9BWIEUKGKUNYEWILIDYVGBYY9PXGPGGQQQOZHZUNOIGHFSJAFYYYK)

**Comment by csielee** [comment]
`deviceproof` iri node also can upload data with MAM

```js
let iota = new IOTA({
  'host' : 'https://node.deviceproof.org',
  'port': '443'
});
```
