### ISSUE TITLE
Deploy Toaster that is web interface of bitbake

### ISSUE THREAD

**Issue by csielee** [DLTcollab/general#96]
Toaster : 
> Toaster is a web interface to the Yocto Project's OpenEmbedded build system. The interface enables you to configure and run your builds. Information about builds is collected and stored in a database. You can use Toaster to configure and start builds on multiple remote build servers.

Reference [toaster-manual](https://www.yoctoproject.org/docs/2.5.1/toaster-manual/toaster-manual.html) to deploy on `node0`

Expect to use yocto build system( bitbake ) more easily and  don't have to put huge yocto build system on the local

[deploy note](https://hackmd.io/s/SJl1TbRKQ)

[tutorial note](https://hackmd.io/s/BJH2Qa497)

**Comment by csielee** [comment]
Toaster Web UI error on http://node0.puyuma.org:9000/toastergui/project/2/layer/1

Web UI raises `TypeError` when click layer info link.

```
Environment:


Request Method: GET
Request URL: http://node0.puyuma.org:9000/toastergui/project/2/layer/1

Django Version: 1.11.4
Python Version: 2.7.14
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'bldcollector',
 'toastermain',
 'bldcontrol',
 'toastergui',
 'orm')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/lee097019/yocto/poky/bitbake/lib/toaster/toastergui/views.py" in layerdetails
  1614.             'layer_source': LayerSource.types_dict(),

Exception Type: TypeError at /toastergui/project/2/layer/1
Exception Value: unbound method types_dict() must be called with LayerSource instance as first argument (got nothing instead)
```

**Comment by csielee** [comment]
`TypeError` is triggered because call class method without instance in python2

solution:

add `@staticmethod` on prefix of this method

```python
class LayerSource(object):
    ... #skip some code   

    #add this modifier
    @staticmethod
    def types_dict():
        ... #skip some code   
        return dictionary
```

Toaster GUI can view the layer's detail 、 recipes of layer、machines provided by layer
http://node0.puyuma.org:9000/toastergui/project/2/layer/1

**Comment by csielee** [comment]
Build image error : 
http://node0.puyuma.org:9000/toastergui/build/3#errors

```
command: unset BBPATH; bash -c "source /home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/oe-init-build-env /home/lee097019/yocto/poky/build-toaster-2; BITBAKE_UI="knotty" /home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/bitbake/bin/bitbake --read /home/lee097019/yocto/poky/build-toaster-2/conf/toaster.conf --read /home/lee097019/yocto/poky/build-toaster-2/conf/toaster-bblayers.conf --server-only -B 0.0.0.0:0" 
Traceback (most recent call last):
  File "/home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/bitbake/bin/bitbake", line 31, in <module>
    import bb
  File "/home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/bitbake/lib/bb/__init__.py", line 79, in <module>
    from bb import fetch2 as fetch
  File "/home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
    import bb.persist_data, bb.utils
  File "/home/lee097019/yocto/poky/_toaster_clones/_git___git.yoctoproject.org_poky_sumo/bitbake/lib/bb/persist_data.py", line 31, in <module>
    import sqlite3
  File "/usr/local/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

Because `bitbake` runs on `python3` not `python2`.

**Comment by csielee** [comment]
Build image success:
http://node0.puyuma.org:9000/toastergui/build/6

solution:
let `Toaster` use `python3`. 
And modify link path of `python3`  to `/usr/bin/python3.6` not `/usr/bin/python3.5`

**Comment by csielee** [comment]
Add tutorial note and video

[tutorial note](https://hackmd.io/s/BJH2Qa497)
[tutorial video](https://www.youtube.com/watch?v=gwkMVea3_YU)
